import type {ReactNode} from 'react';
import {useText} from './i18n';
export const repo='https://github.com/forge-language/forge';
export type Go=(path:string)=>void;
export function Link({to,go,children}:{to:string;go:Go;children:ReactNode}) {return <a className="link" href={to} onClick={e=>{e.preventDefault();go(to)}}>{children}</a>}
export function Title({label,title,children}:{label:string;title:string;children?:ReactNode}) {return <div className="mb-12 max-w-3xl"><p className="eyebrow mb-4">{label}</p><h1 className="text-4xl md:text-6xl font-semibold mb-6">{title}</h1><div className="text-muted leading-8">{children}</div></div>}
const pillars=[
 ['01 / OWNERSHIP','Safe ownership.','GC에 의존하지 않는 메모리 안전성을 목표로 합니다. 현재 own·move와 일부 use-after-move 진단이 구현되어 있습니다. 완전한 borrow checker와 data-race 검증은 로드맵에 있습니다.'],
 ['02 / CONCURRENCY','Massive concurrency.','경량 프로세스와 코루틴을 M:N 워커 스케줄러에서 실행합니다. Linux epoll·macOS kqueue를 사용하며, 장애 복구와 대규모 안정성 검증을 계속 개발합니다.'],
 ['03 / PERFORMANCE','Native speed.','Forge 소스는 C 백엔드를 거쳐 네이티브 실행 파일이 됩니다. 컴파일러와 실제 서버의 측정 코드·환경·원시 결과를 함께 공개합니다.']
];
const pillarEnglish:Record<string,string>={
 '01 / OWNERSHIP':'Aims for memory safety without relying on garbage collection. Owned values, moves, and some use-after-move diagnostics exist today. A complete borrow checker and data-race verification remain on the roadmap.',
 '02 / CONCURRENCY':'Runs lightweight processes and coroutines on an M:N worker scheduler, using Linux epoll and macOS kqueue. Fault recovery and validation at scale are still under development.',
 '03 / PERFORMANCE':'Compiles Forge through a C backend into native executables. Compiler and server measurements include source code, environment details, and raw results.'
};
export function Home({go,install}:{go:Go;install:string}) {const t=useText();return <>
 <section className="content grid lg:grid-cols-[1.2fr_1fr] gap-14 py-16 md:py-24"><div><p className="eyebrow mb-7">FORGE / EXPERIMENTAL SYSTEMS LANGUAGE</p><h1 className="hero-title text-5xl md:text-7xl font-semibold leading-[1.08] mb-7">Safe ownership.<br/>Massive concurrency.<br/>Native speed.</h1><p className="text-lg text-muted leading-8 max-w-xl mb-5">{t('An experimental systems programming language built in the open by people and AI agents.','사람과 AI 에이전트가 함께 공개적으로 만드는 실험적 시스템 프로그래밍 언어.')}</p><p className="text-sm text-muted leading-7 mb-8">{t('These are design goals. Explore the current implementation and its limits, run the code, and help shape the language.','세 문장은 Forge의 설계 목표입니다. 현재 구현과 한계를 확인하고, 직접 실행하며 개발에 참여하세요.')}</p><div className="flex flex-wrap gap-3"><a className="button" href="/play" onClick={e=>{e.preventDefault();go('/play')}}>{t('Try Forge','Forge 실행')}</a><a className="secondary" href={repo} target="_blank" rel="noreferrer">GitHub ↗</a><a className="secondary" href="/docs" onClick={e=>{e.preventDefault();go('/docs')}}>{t('Documentation','문서')}</a></div><div className="mt-6"><Link to="/agents" go={go}>{t('Watch the agents work →','에이전트 개발 활동 →')}</Link></div></div><div className="self-center min-w-0"><div className="bg-ink text-paper font-mono text-xs px-5 py-3 flex justify-between"><span>main.fg</span><span>native / preview</span></div><pre className="code text-base leading-8"><code>{'fn square(value: int): int {\n  return value * value;\n}\n\nnative main {\n  println("Hello, Forge!");\n  println(square(12));\n  return 0;\n}'}</code></pre><div className="font-mono text-xs text-muted pt-4">$ forge main.fg -o hello &amp;&amp; ./hello</div></div></section>
 <section className="border-y border-line"><div className="content grid md:grid-cols-3 gap-10 py-14">{pillars.map(([n,h,p])=><article key={n}><p className="eyebrow mb-4">{n}</p><h2 className="text-2xl font-semibold mb-4">{h}</h2><p className="text-muted text-sm leading-7">{t(pillarEnglish[n],p)}</p></article>)}</div></section>
 <section className="content py-16 grid md:grid-cols-2 gap-12"><div><p className="eyebrow mb-4">BUILT IN THE OPEN</p><h2 className="text-3xl md:text-4xl font-semibold leading-tight mb-6">{t('Open development','공개 개발')}</h2><p className="text-muted leading-8 mb-6">{t('Agents help plan, implement, test, and review changes. People decide language design, approve changes, and merge pull requests. Follow the actual work and its validation.','에이전트는 계획·구현·테스트·리뷰에 참여합니다. 사람은 언어 설계와 변경 승인, 병합을 결정합니다. 실제 PR과 검증 결과를 따라가 보세요.')}</p><Link to="/agents" go={go}>{t('Follow development →','개발 활동 보기 →')}</Link></div><div className="border-t border-ink">{[[t('Learn','배우기'),t('Read the implemented syntax and architecture.','구현된 문법과 구조를 읽으세요.'),'/docs/syntax'],[t('Try','실행하기'),t('Run code without installing anything.','설치 없이 코드를 실행하세요.'),'/play'],[t('Watch','지켜보기'),t('Follow real issues and pull requests.','실제 이슈와 PR을 확인하세요.'),'/agents'],[t('Contribute','기여하기'),t('Help with ideas, docs, tests, and code.','아이디어·문서·테스트·코드로 참여하세요.'),'/contribute']].map(([name,text,url])=><a key={name} className="flex gap-6 border-b border-line py-5" href={url} onClick={e=>{e.preventDefault();go(url)}}><span className="font-mono text-accent w-24 shrink-0">{name}</span><span className="text-sm text-muted">{text}</span><span className="ml-auto">↗</span></a>)}</div></section>
 <section className="border-y border-line"><div className="content py-14 grid md:grid-cols-2 gap-12"><div><h2 className="text-3xl font-semibold mb-5">{t('Here is the benchmark.','벤치마크를 확인하세요.')}<br/>{t('Run it yourself.','직접 재현하세요.')}</h2><p className="text-muted leading-7 mb-5">{t('Measurements include hardware, compiler options, and workloads, alongside the limitations of results collected on a shared host.','하드웨어·컴파일 옵션·작업량을 기록합니다. 공유 호스트에서 측정한 결과의 한계도 공개합니다.')}</p><Link to="/benchmarks" go={go}>{t('Benchmarks and reproduction steps →','벤치마크와 재현 방법 →')}</Link></div><div><h2 className="text-3xl font-semibold mb-5">{t('Bring an idea.','아이디어를 가져오세요.')}<br/>{t('Work with the agents.','에이전트와 함께 개발하세요.')}</h2><p className="text-muted leading-7 mb-5">{t('Reproducible bug reports, specifications, tests, and reviews all move the project forward. Bring an idea and work with the contributors.','모든 코드를 직접 작성할 필요는 없습니다. 재현 가능한 버그, 명세, 테스트와 리뷰도 프로젝트를 발전시킵니다.')}</p><Link to="/community" go={go}>{t('Join the community →','커뮤니티 참여 →')}</Link></div></div></section>
 <section className="content py-16 grid md:grid-cols-[1fr_1.4fr] gap-10"><div><h2 className="text-3xl font-semibold mb-4">{t('Run your first program.','5분 안에 첫 실행.')}</h2><p className="text-muted leading-7">{t('Linux x86_64 · glibc 2.35+ · C compiler.','Linux x86_64 · glibc 2.35+ · C 컴파일러.')}<br/>{t('Installs preview tools in ~/.forge.','preview 도구를 ~/.forge에 설치합니다.')}</p></div><div><pre className="code"><code>{install+'\nsource "$HOME/.forge/env"\nforge init hello-app\ncd hello-app\nforge run'}</code></pre><Link to="/docs" go={go}>{t('Installation and supported platforms →','설치 안내와 지원 범위 →')}</Link></div></section>
 </>}
