import React, { useEffect, useState, type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
type Release = { javascript?:{entry:string;package_file:string}; name:string; version:string; description:string; repository_url:string; git_commit:string; module:string; license:string; dependencies:Record<string,string>; native?:{library:string;cmake_target:string;pkg_config:string[]}; readme?:string; published_at?:string };
type Detail = {name:string;owner:string;versions:Release[]};
type User = {sub:string;role:string;exp:number};
const tokenKey='forge_registry_token';
async function api<T>(path:string, options:RequestInit={}):Promise<T> {
 const token=sessionStorage.getItem(tokenKey);const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} : {}),...options.headers}});
 const body=await response.json();if(!response.ok)throw new Error(body.message??body.error??`HTTP ${response.status}`);return body;
}
function Code({children}:{children:string}) {const[copied,setCopied]=useState(false);return <div className="relative"><pre className="code pr-20"><code>{children}</code></pre><button className="absolute right-3 top-3 text-xs border border-line bg-paper px-2 py-1" onClick={()=>void navigator.clipboard.writeText(children).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),1500)}).catch(()=>setCopied(false))}>{copied?'복사됨':'복사'}</button></div>}
function App(){
 const[path,setPath]=useState(location.pathname);const[user,setUser]=useState<User|null>(null);const[authError,setAuthError]=useState('');
 useEffect(()=>{const pop=()=>setPath(location.pathname);window.addEventListener('popstate',pop);const fragment=new URLSearchParams(location.hash.slice(1));const token=fragment.get('token');if(token){sessionStorage.setItem(tokenKey,token);history.replaceState({},'',location.pathname)}if(sessionStorage.getItem(tokenKey))void api<User>('/api/me').then(setUser).catch(()=>{sessionStorage.removeItem(tokenKey);setAuthError('로그인 세션이 만료되었습니다.')});if(new URLSearchParams(location.search).has('error'))setAuthError('GitHub 로그인을 완료하지 못했습니다. OAuth 설정을 확인해 주세요.');return()=>window.removeEventListener('popstate',pop)},[]);
 function go(url:string){history.pushState({},'',url);setPath(url);window.scrollTo(0,0)}
 const page=path.startsWith('/packages/')?'detail':path==='/packages'?'packages':path==='/docs'?'docs':path==='/publish'?'publish':'home';
 const install=`curl -fsSL ${location.origin}/install.sh | bash`;
 return <><header className="border-b border-line"><div className="content flex min-h-20 items-center justify-between gap-5 flex-wrap py-4"><a href="/" onClick={e=>{e.preventDefault();go('/')}} className="font-mono text-2xl font-bold tracking-tight">forge<span className="text-accent">_</span></a><nav aria-label="주 메뉴" className="flex items-center gap-5 text-sm"><a href="/docs" onClick={e=>{e.preventDefault();go('/docs')}} aria-current={page==='docs'?'page':undefined}>문서</a><a href="/packages" onClick={e=>{e.preventDefault();go('/packages')}} aria-current={page==='packages'?'page':undefined}>모듈</a><a href="/publish" onClick={e=>{e.preventDefault();go('/publish')}}>배포</a><a href="https://github.com/forge-language/forge-platform" target="_blank" rel="noreferrer">GitHub ↗</a></nav></div></header>
 {authError&&<div className="content py-4 text-sm" role="alert">{authError}</div>}
 <main>{page==='home'?<><section className="content grid lg:grid-cols-[1.2fr_1fr] gap-12 pt-16 pb-20 md:pt-24"><div><p className="font-mono text-sm text-muted mb-7">FORGE / 0.3.0 PREVIEW</p><h1 className="text-5xl md:text-7xl leading-[1.08] font-semibold mb-7">언어에서 서버까지.<br/>직접 만드는 Forge.</h1><p className="text-muted text-lg leading-8 max-w-lg mb-8">C로 컴파일되는 작은 언어에 서버 모듈과 패키지 도구를 더했습니다. 구현된 기능과 현재 한계를 문서에서 확인하고, 실제 프로젝트로 시험해 보세요.</p><div className="flex gap-3"><a className="button" href="/docs" onClick={e=>{e.preventDefault();go('/docs')}}>설치하고 시작하기</a><a className="secondary" href="/packages" onClick={e=>{e.preventDefault();go('/packages')}}>모듈 살펴보기</a></div></div><div className="self-center"><div className="bg-ink text-paper font-mono text-xs px-5 py-3 flex justify-between"><span>main.fg</span><span>native → C → executable</span></div><pre className="bg-white border border-line text-sm md:text-base leading-8 p-6 overflow-auto"><code>{`import strings;

fn greet(name: string): string {
  return str_concat("Hello, ", name);
}

native main {
  println(greet("Forge"));
  return 0;
}`}</code></pre><div className="font-mono text-xs text-muted px-5 pt-3">$ forge main.fg -o hello &amp;&amp; ./hello</div></div></section><section className="border-y border-line"><div className="content grid md:grid-cols-3 gap-8 py-12">{[['네이티브 실행','C 백엔드와 64비트 정수. OS·네트워크·암호화는 네이티브 브리지로 연결합니다.'],['버전이 고정된 모듈','Forge API를 독립 저장소로 분리했습니다. 버전과 Git 커밋을 lock 파일에 기록합니다.'],['실제 서버로 검증','포트폴리오 API와 이 사이트의 레지스트리 서버 로직을 Forge로 작성했습니다.']].map(([h,p])=><div key={h}><h2 className="text-xl font-semibold mb-3">{h}</h2><p className="text-muted leading-7 text-sm">{p}</p></div>)}</div></section><section className="content py-16 grid md:grid-cols-[1fr_1.4fr] gap-10"><div><h2 className="text-3xl font-semibold mb-4">터미널에서 시작하세요.</h2><p className="text-muted leading-7">Linux x86_64, glibc 2.35 이상.<br/>C 컴파일러가 필요합니다. 설치에는 sudo가 필요하지 않습니다.</p></div><div><Code>{install}</Code><p className="text-sm text-muted mt-3">SHA-256 검증 후 ~/.forge에 설치합니다. 현재 배포는 preview입니다.</p></div></section></>:null}
 {page==='docs'?<section className="content py-14 grid md:grid-cols-[180px_1fr] gap-12"><aside className="text-sm text-muted space-y-4"><a className="block link" href="#install">설치</a><a className="block link" href="#modules">모듈 관리자</a><a className="block link" href="#browser">브라우저 출력</a><a className="block link" href="#limits">현재 한계</a></aside><article className="max-w-3xl space-y-10"><div><h1 className="text-4xl font-semibold mb-3">Forge 시작하기</h1><p className="text-muted">실행 가능한 예제와 배포 도구의 현재 지원 범위입니다.</p></div><div id="install"><h2 className="text-2xl font-semibold mb-4">설치와 첫 실행</h2><Code>{install}</Code><Code>{`source "$HOME/.forge/env"
forge --version
mkdir hello && cd hello
forge init hello-app
forge run`}</Code><p className="mt-4 text-sm leading-7">지원: Linux x86_64 / glibc 2.35+ (Ubuntu 22.04 이상). curl, tar, sha256sum, cc가 필요합니다. 네이티브 모듈 빌드에는 Git, CMake, pkg-config와 해당 개발 라이브러리도 설치하세요.</p><Code>{`forge update
forge uninstall`}</Code></div><div id="modules"><h2 className="text-2xl font-semibold mb-4">모듈 관리자</h2><Code>{`forge pkg search postgres
forge pkg add forge-postgres 0.1.0
forge pkg install
forge build
forge pkg list
forge pkg remove forge-postgres`}</Code><p className="mt-4 text-sm leading-7">forge.json에는 정확한 x.y.z 버전을, forge.lock에는 저장소와 40자리 커밋을 기록합니다. 의존성 충돌과 순환 참조는 설치 오류로 처리합니다. 버전 범위와 prerelease 모듈은 아직 지원하지 않습니다.</p><p className="mt-4 text-sm leading-7">PostgreSQL 모듈 개발 패키지(Ubuntu): libpq-dev. Web 모듈: libmicrohttpd-dev libjson-c-dev libcurl4-openssl-dev libssl-dev. 네이티브 모듈은 빌드 시 해당 저장소의 CMake 코드를 실행합니다.</p></div><div id="browser"><h2 className="text-2xl font-semibold mb-4">브라우저용 JavaScript 출력</h2><Code>{`forge main.fg --emit-js -o main.js\n# 브라우저 모듈과 함께 번들링\nforge build --emit-js`}</Code><p className="mt-4 text-sm leading-7">기본 함수·제어 흐름·모듈·정수 연산을 JavaScript로 출력합니다. extern 함수는 ForgeNative 브리지로 연결합니다. 프로세스·코루틴·네이티브 라이브러리 연결은 이 출력 모드에서 지원하지 않습니다.</p></div><div id="limits"><h2 className="text-2xl font-semibold mb-4">현재 한계</h2><p className="text-sm leading-7">Forge는 실험 단계입니다. 완전한 타입 검사·소유권 검사와 Rust 수준의 메모리 안전성은 아직 제공하지 않습니다. 서버 모듈은 libpq, libmicrohttpd, OpenSSL 등을 사용하며, DB 연결 풀과 HTTP 작업 스레드의 수가 처리량에 영향을 줍니다. 이 사이트의 UI는 React·TypeScript·Tailwind로 작성했습니다.</p></div></article></section>:null}
 {page==='packages'?<Packages go={go}/>:null}
 {page==='detail'?<Package name={decodeURIComponent(path.split('/')[2]??'')} go={go}/>:null}
 {page==='publish'?<Publish user={user} logout={()=>{sessionStorage.removeItem(tokenKey);setUser(null)}}/>:null}
 </main><footer className="border-t border-line mt-12"><div className="content py-8 flex flex-wrap justify-between gap-5 text-sm text-muted"><span className="font-mono">FORGE / EXPERIMENTAL</span><span>서버: Forge · 웹: React + TypeScript + Tailwind</span><a className="link" href="https://github.com/Helloworld0822/portfolio-platform/pull/1">포트폴리오 마이그레이션</a></div></footer></>
}
function Packages({go}:{go:(s:string)=>void}) {const[q,setQ]=useState('');const[items,setItems]=useState<Release[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{let current=true;const timer=setTimeout(()=>{setLoading(true);void api<Release[]>(`/api/packages?q=${encodeURIComponent(q)}`).then(r=>{if(current){setItems(r);setError('')}}).catch(e=>{if(current)setError(String(e.message))}).finally(()=>{if(current)setLoading(false)})},200);return()=>{current=false;clearTimeout(timer)}},[q]);return <section className="content py-14"><div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-10"><div><h1 className="text-4xl font-semibold mb-3">모듈 레지스트리</h1><p className="text-muted">독립 저장소에서 관리하는 Forge 모듈을 찾아보세요.</p></div><label className="w-full md:w-80 text-sm">이름 또는 설명 검색<input type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="postgres, web…" className="mt-2"/></label></div>{error?<p role="alert">레지스트리에 연결하지 못했습니다: {error}</p>:loading?<p role="status">모듈을 불러오는 중…</p>:items.length===0?<p>검색 결과가 없습니다.</p>:<div className="border-t border-line">{items.map(item=><a className="block border-b border-line py-7 hover:bg-white/60 px-4 -mx-4" href={`/packages/${item.name}`} key={item.name} onClick={e=>{e.preventDefault();go(`/packages/${item.name}`)}}><div className="flex items-baseline justify-between gap-4"><h2 className="font-mono text-xl font-semibold">{item.name}</h2><span className="font-mono text-sm text-muted">{item.version}</span></div><p className="text-muted my-3">{item.description}</p><div className="text-xs font-mono text-muted">{item.license} · {item.javascript?'browser bridge':item.native?'native bridge':'Forge module'} · {item.module}</div></a>)}</div>}</section>}
function Package({name,go}:{name:string;go:(s:string)=>void}) {const[data,setData]=useState<Detail|null>(null);const[index,setIndex]=useState(0);const[error,setError]=useState('');useEffect(()=>{setData(null);setIndex(0);void api<Detail>(`/api/packages/${encodeURIComponent(name)}`).then(setData).catch(e=>setError(e.message))},[name]);const release=data?.versions[index];return <section className="content py-14"><a className="link text-sm" href="/packages" onClick={e=>{e.preventDefault();go('/packages')}}>← 모듈 목록</a>{error?<p role="alert" className="mt-8">{error}</p>:!release?<p role="status" className="mt-8">불러오는 중…</p>:<><div className="grid md:grid-cols-[1fr_260px] gap-12 mt-10"><article><h1 className="font-mono text-4xl font-semibold mb-4">{release.name}</h1><p className="text-lg text-muted mb-8">{release.description}</p><Code>{`forge pkg add ${release.name} ${release.version}`}</Code><h2 className="text-2xl font-semibold mt-10 mb-4">사용 안내</h2><pre className="whitespace-pre-wrap font-sans leading-7 text-sm border-t border-line pt-5">{release.readme??'자세한 API와 빌드 방법은 소스 저장소의 README를 확인하세요.'}</pre><h2 className="text-2xl font-semibold mt-10 mb-4">의존성</h2>{Object.keys(release.dependencies).length?<pre className="code">{JSON.stringify(release.dependencies,null,2)}</pre>:<p className="text-sm text-muted">Forge 모듈 의존성 없음.</p>}{release.native&&<><h3 className="text-lg font-semibold mt-6 mb-3">네이티브 개발 라이브러리</h3><p className="font-mono text-sm">{release.native.pkg_config.join(', ')}</p></>}</article><aside className="border-t border-ink pt-5 text-sm space-y-6"><div><label htmlFor="version" className="block text-muted mb-2">버전</label><select id="version" className="w-full border border-line bg-white p-2" value={index} onChange={e=>setIndex(Number(e.target.value))}>{data?.versions.map((v,i)=><option key={v.version} value={i}>{v.version}</option>)}</select></div><div><p className="text-muted mb-2">소유자</p><p>{data?.owner}</p></div><div><p className="text-muted mb-2">라이선스</p><p>{release.license}</p></div><div><p className="text-muted mb-2">고정 커밋</p><code className="break-all text-xs">{release.git_commit}</code></div><a href={`${release.repository_url}/tree/${release.git_commit}`} className="link inline-block" target="_blank" rel="noreferrer">소스 저장소 ↗</a><details><summary className="cursor-pointer">릴리스 manifest</summary><pre className="text-xs overflow-x-auto mt-3">{JSON.stringify(release,null,2)}</pre></details></aside></div></>}</section>}
const template:Release={name:'my-module',version:'0.1.0',description:'모듈 설명',repository_url:'https://github.com/YOUR_NAME/my-module',git_commit:'0'.repeat(40),module:'module.fg',license:'MIT',dependencies:{}};
function Publish({user,logout}:{user:User|null;logout:()=>void}){const[text,setText]=useState(JSON.stringify(template,null,2));const[result,setResult]=useState('');const[busy,setBusy]=useState(false);const[tokenVisible,setTokenVisible]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const value=JSON.parse(text);await api('/api/packages',{method:'POST',body:JSON.stringify(value)});setResult('릴리스를 배포했습니다. 모듈 목록에서 확인하세요.')}catch(e){setResult(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}return <section className="content max-w-4xl py-14"><h1 className="text-4xl font-semibold mb-4">모듈 배포</h1><p className="text-muted leading-7 mb-8">GitHub 저장소의 커밋을 고정해 릴리스를 등록합니다. 같은 이름과 버전의 릴리스는 덮어쓸 수 없습니다. 새 버전으로 변경 사항을 배포하세요.</p>{!user?<><a className="button" href="/api/auth/github/login?state=%2Fpublish">GitHub로 로그인</a><p className="text-sm text-muted mt-4">운영자가 GitHub OAuth 앱을 설정한 후 사용할 수 있습니다.</p></>:<><div className="flex justify-between border-y border-line py-4 mb-8 text-sm"><span>{user.sub} · {user.role}</span><button onClick={logout} className="link">로그아웃</button></div><form onSubmit={e=>void submit(e)}><label htmlFor="manifest" className="block font-semibold mb-3">릴리스 manifest (JSON)</label><textarea id="manifest" className="font-mono text-sm leading-6 min-h-96" value={text} onChange={e=>setText(e.target.value)} spellCheck={false}/><button className="button mt-5" disabled={busy}>{busy?'배포하는 중…':'릴리스 배포'}</button></form><div className="mt-10 border-t border-line pt-5"><button className="link text-sm" onClick={()=>setTokenVisible(!tokenVisible)}>{tokenVisible?'CLI 토큰 숨기기':'CLI 배포용 토큰 표시'}</button>{tokenVisible&&<><p className="text-xs text-muted my-3">현재 로그인 토큰입니다. 본인의 터미널에서만 사용하고 공유하지 마세요.</p><Code>{`export FORGE_TOKEN='${sessionStorage.getItem(tokenKey)??''}'
forge pkg publish module.json`}</Code></>}</div></>}{result&&<p role="status" className="mt-6 p-4 border border-line">{result}</p>}</section>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
