import {useEffect,useRef,useState} from 'react';
import {Title} from './home';
const examples:Record<string,string>={
 'Hello Forge':'native main {\n  println("Hello, Forge!");\n  return 0;\n}',
 'Functions':'fn fibonacci(n: int): int {\n  if (n < 2) { return n; }\n  return fibonacci(n - 1) + fibonacci(n - 2);\n}\nnative main {\n  println(fibonacci(12));\n  return 0;\n}',
 'UTF-8 strings':'import strings;\nnative main {\n  let greeting: string = "안녕하세요, Forge!";\n  println(greeting);\n  println(str_len(greeting));\n  return 0;\n}',
 '64-bit integers':'native main {\n  let value: int = 9007199254740993;\n  println(value + 2);\n  return 0;\n}'
};
export function Playground(){
 const[source,setSource]=useState(examples['Hello Forge']);const[output,setOutput]=useState('Run을 눌러 실행하세요.');const[js,setJS]=useState('');const[busy,setBusy]=useState(false);const[ready,setReady]=useState(false);const frame=useRef<HTMLIFrameElement>(null);const worker=useRef<Worker|null>(null);const deadline=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 useEffect(()=>{function receive(event:MessageEvent){if(event.source!==frame.current?.contentWindow)return;if(event.data?.type==='ready')setReady(true);if(event.data?.type==='result'){clearTimeout(deadline.current);setBusy(false);setOutput((event.data.output||'')+(event.data.error?'\n'+event.data.error:'')||'실행 완료 (출력 없음).')}}window.addEventListener('message',receive);return()=>{window.removeEventListener('message',receive);worker.current?.terminate();clearTimeout(deadline.current)}},[]);
 function run(){if(!ready||busy)return;if(new TextEncoder().encode(source).length>65536){setOutput('코드는 64 KiB 이하로 입력하세요.');return}setBusy(true);setJS('');setOutput('컴파일하는 중…');const compiler=new Worker('/playground/compile-worker.js',{type:'module'});worker.current=compiler;function fail(message:string){clearTimeout(deadline.current);compiler.terminate();setBusy(false);setOutput(message)}deadline.current=setTimeout(()=>fail('컴파일 또는 실행 시간 제한을 초과했습니다.'),15000);compiler.onerror=event=>{event.preventDefault();fail(event.message||'컴파일러를 불러오지 못했습니다.')};compiler.onmessage=({data})=>{compiler.terminate();if(data.error){fail(data.error);return}setJS(data.javascript);setOutput('실행하는 중…');frame.current?.contentWindow?.postMessage({type:'run',javascript:data.javascript},'*')};compiler.postMessage({source})}
 return <section className="content py-16"><Title label="TRY / BROWSER PLAYGROUND" title="Write. Run. Explore.">실제 Forge 파서와 JavaScript 백엔드를 WebAssembly로 실행합니다. 코드와 실행 결과는 브라우저에 머뭅니다.</Title><div className="flex flex-wrap justify-between items-center gap-4 mb-5"><label className="text-sm">예제 <select className="border border-line bg-white px-3 py-2 ml-2" aria-label="예제" defaultValue="Hello Forge" onChange={e=>setSource(examples[e.target.value])}>{Object.keys(examples).map(name=><option key={name}>{name}</option>)}</select></label><button className="button" disabled={busy||!ready} onClick={run}>{!ready?'실행 환경 준비 중…':busy?'실행 중…':'Run →'}</button></div><div className="grid lg:grid-cols-2 gap-6"><div><label htmlFor="source" className="block eyebrow mb-3">MAIN.FG</label><textarea id="source" spellCheck={false} className="font-mono text-sm leading-7 min-h-80" value={source} onChange={e=>setSource(e.target.value)}/></div><div><h2 className="eyebrow mb-3">OUTPUT</h2><pre className="code min-h-80 whitespace-pre-wrap break-words" role="status">{output}</pre></div></div><p className="text-sm text-muted leading-7 mt-6">지원: native main, 함수·반복문·정수·일부 문자열 함수. 프로세스·코루틴·네이티브 모듈·파일·네트워크 API는 지원하지 않습니다. 코드 64 KiB, 실행 2초, 출력 16,000자 제한.</p>{js&&<details className="mt-6"><summary className="link cursor-pointer">생성된 JavaScript 보기</summary><pre className="code mt-4 text-xs"><code>{js}</code></pre></details>}<iframe ref={frame} title="Forge 실행 샌드박스" src="/playground/runner.html" sandbox="allow-scripts" onLoad={()=>setReady(true)} className="sr-only" tabIndex={-1} aria-hidden="true"/></section>
}
