import {useEffect,useState,Fragment} from 'react';
import {Title} from './home';
import {useText} from './i18n';
import {useLiveData,viewerLink,type BenchmarkData} from './live-data';
import {useLiveJson,type LiveManifest} from './public-live-data';
const MAX_BYTES=1024*1024;
export function safeMaterialPath(value:string){return /^\/(?:project|reports|materials|live\/snapshots\/[a-f0-9]{24}\/(?:documents|reports|benchmarks))\/[a-zA-Z0-9_./% -]+\.(?:md|json)$/.test(value)&&!value.split('/').some(part=>{try{return decodeURIComponent(part)==='..'||decodeURIComponent(part).includes('\\')||decodeURIComponent(part).includes('/')}catch{return true}})}
function safeLink(value:string){try{const url=new URL(value,window.location.origin);return url.protocol==='https:'||url.origin===window.location.origin&&url.protocol===window.location.protocol?url.href:undefined}catch{return undefined}}
function inline(text:string){return text.split(/(`[^`]+`|\[[^\]]+\]\([^\s)]+\))/g).map((part,index)=>{if(part.startsWith('`')&&part.endsWith('`'))return <code key={index}>{part.slice(1,-1)}</code>;const match=part.match(/^\[([^\]]+)\]\(([^\s)]+)\)$/);if(match){const href=safeLink(match[2]);return href?<a className="link" href={href} key={index} rel="noopener noreferrer">{match[1]}</a>:<Fragment key={index}>{match[1]}</Fragment>}return part})}
function Markdown({text}:{text:string}){const lines=text.split('\n'),nodes=[];for(let index=0;index<lines.length;index++){const line=lines[index];if(line.startsWith('```')){const code=[];while(++index<lines.length&&!lines[index].startsWith('```'))code.push(lines[index]);nodes.push(<pre className="code my-6 overflow-auto" key={index}><code>{code.join('\n')}</code></pre>);continue}const heading=line.match(/^(#{1,6})\s+(.+)/);if(heading){const content=inline(heading[2]);nodes.push(heading[1].length===1?<h1 className="text-3xl font-semibold mt-10 mb-5" key={index}>{content}</h1>:heading[1].length===2?<h2 className="text-2xl font-semibold mt-8 mb-4" key={index}>{content}</h2>:<h3 className="text-xl font-semibold mt-6 mb-3" key={index}>{content}</h3>);continue}if(!line.trim())continue;nodes.push(<p className="leading-8 my-3 whitespace-pre-wrap break-words" key={index}>{inline(line)}</p>)}return <article>{nodes}</article>}
export function Viewer(){const t=useText(),{data}=useLiveData<BenchmarkData>('/benchmarks.json'),{data:live}=useLiveJson<LiveManifest>('/live/manifest.json');const path=new URLSearchParams(window.location.search).get('file')||'';const [content,setContent]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
useEffect(()=>{const controller=new AbortController();setContent('');setError('');setLoading(Boolean(path));if(!path)return()=>controller.abort();if(!safeMaterialPath(path)){setError('invalid');setLoading(false);return()=>controller.abort()}async function load(){try{const response=await fetch(path,{signal:controller.signal,cache:'no-cache'});if(!response.ok)throw new Error('unavailable');const length=Number(response.headers.get('content-length'));if(length>MAX_BYTES)throw new Error('large');const reader=response.body?.getReader();if(!reader)throw new Error('unavailable');const chunks:Uint8Array[]= [];let total=0;while(true){const {value,done}=await reader.read();if(done)break;total+=value.length;if(total>MAX_BYTES){await reader.cancel();throw new Error('large')}chunks.push(value)}const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length}let text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(path.endsWith('.json'))text=JSON.stringify(JSON.parse(text),null,2);setContent(text)}catch(e){if(controller.signal.aborted)return;setError(e instanceof Error?e.message:'unavailable')}finally{if(!controller.signal.aborted)setLoading(false)}}void load();return()=>controller.abort()},[path]);
const material=data?.reports.find(item=>item.file===path);return <section className="content py-16"><Title label="MATERIALS / SOURCE DOCUMENTS" title={t('Document viewer','자료 뷰어')}>{t('Read project documents, benchmark reports and raw JSON without leaving the site.','프로젝트 문서, 벤치마크 보고서와 원시 JSON을 사이트에서 읽습니다.')}</Title>{!path?<div className="space-y-5">{[['Language specification','/project/LANGUAGE_SPEC.md'],['Architecture','/project/ARCHITECTURE.md'],['Roadmap','/project/ROADMAP.md'],['Contributing','/project/CONTRIBUTING.md']].map(([title,file])=><a key={file} className="block link" href={viewerLink(file)}>{title}</a>)}{[...(live?.documents??[]),...(live?.reports??[])].map(item=><a key={item.url} className="block link" href={viewerLink(item.url)}>{item.repository} / {item.title}</a>)}{live?.latest_benchmark?.url&&<a className="block link" href={viewerLink(live.latest_benchmark.url)}>{t('Latest measured benchmark JSON','최신 벤치마크 측정 JSON')}</a>}{data?.reports.map(item=><a key={item.id} className="block link" href={viewerLink(item.file)}>{item.repository||t('Published snapshot','공개 스냅샷')} / {item.title} ({item.format})</a>)}</div>:<><div className="flex flex-wrap gap-5 text-sm mb-8"><a className="link" href="/view">{t('All materials','전체 자료')}</a>{safeMaterialPath(path)&&<a className="link" href={path} download>{t('Download source','원본 다운로드')}</a>}{material?.source&&safeLink(material.source)&&<a className="link" href={material.source} rel="noopener noreferrer">GitHub ↗</a>}</div><p className="font-mono text-sm text-muted break-all">{path}</p>{loading?<p role="status" className="mt-8">{t('Loading document…','문서를 불러오는 중…')}</p>:error?<p role="alert" className="mt-8">{error==='large'?t('This document exceeds the 1 MB viewer limit.','이 문서는 뷰어의 1 MB 제한을 초과합니다.'):t('The document is unavailable or the path is invalid.','자료를 불러올 수 없거나 경로가 올바르지 않습니다.')}</p>:path.endsWith('.json')?<pre className="code mt-8 overflow-auto"><code>{content}</code></pre>:<Markdown text={content}/>}</>}</section>}
